---
# task create
- name: Get parameters from environment or shell variables
  set_fact:
    aws_access_key: "{{ aws_access_key | default(lookup('env', 'AWS_ACCESS_KEY_ID')) }}"
    aws_secret_key: "{{ aws_secret_key | default(lookup('env', 'AWS_SECRET_ACCESS_KEY')) }}"

# Copy local .template asset to s3 before running cloudformation (During stack creation we source the template from s3)
- name: PUT pipeline cloudformation template to s3 bucket
  aws_s3:
    bucket: "{{ bucket_name }}"
    object: "{{cf_s3_prefix}}/{{ cf_template_file }}"
    src: "{{ cf_template_path }}/{{ cf_template_file }}"
    mode: put

#- pause:

# Create a stack, pass in template from a URL, disable rollback if stack creation fails,
# pass in some parameters to the template, provide tags for resources created.
- name: create a stack, pass in the template via an URL
  cloudformation:
    stack_name: "{{ stack_name }}"
    state: present
    region: "{{ region }}"
    disable_rollback: true
    template_url: "https://s3.amazonaws.com/{{ bucket_name }}/{{ cf_s3_prefix }}/{{ cf_template_file }}"
    template_parameters:
      GithubUsername: "{{ github_username}}"
      GithubRepo: "{{ github_repo }}"
      GithubBranch: "{{ github_branch }}"
      SlackUsername: "{{ slack_username }}"
      SlackHook: "{{ slack_hook }}"
      SlackChannel: "{{ slack_channel }}"
      #IconEmoji: "{{ icon_emoji }}" # Custom Emoji added to my slack 'siliconmaze' workspace
      #LambdaName: "{{ lambda_name }}"

    tags:
      Stack: "{{ stack_name }}"
    ## Ansible version 2.8
    #capabilities: "CAPABILITY_IAM"