---
# vars file for build-pipeline

stack_name: "slack-pipeline"
lambda_name: "Slack-Alerter"
bucket_name: "siliconmaze-cloudformation-store"
cf_template_path: "files/cloudformation"
cf_template_file: "pipeline.yml"
cf_s3_prefix: "ansible/build-pipeline/cloudformation"
region: "eu-west-2"
#able-solutions personal access token called AWS CodePipeline SiliconMaze in GitHub added to AWS secret Manager
github_username: "able-solutions" #Github username, not email
github_repo: "aws-github-slack-webhook"
github_branch: "SR-001"
slack_username: "GitHub via AWS" #Just a name for the entity that creates the channel message
#able-solutions slack hook, now in secrets manager
slack_channel: "#repo_alerts"
icon_emoji: ":github:"